### ISSUE TITLE
Blank app and errors when running the packaged app in a fresh project

### ISSUE THREAD

**Issue by jagthedrummer** [adopted-ember-addons/ember-electron#1065]
```
$ ember --version
ember-cli: 3.28.5
node: 14.19.0
os: darwin x64
```

```
$ ember new testproject
$ cd testproject
$ ember install ember-electron
$ ember electron:make
```

It appears to make successfully with no errors reported and an executable app is produced at `electron-app/out/testproject-darwin-x64/testproject.app`. When I launch that I get a blank app screen, and the following error is in the developer console:

```
Uncaught TypeError: Cannot destructure property 'manager' of 'e' as it is null.
    at u.resolvedComponent (vendor-f9cd02b2d977eb709718176b86e47f9c.js:2466:28)
    at vendor-f9cd02b2d977eb709718176b86e47f9c.js:2361:5
    at ie (vendor-f9cd02b2d977eb709718176b86e47f9c.js:2361:30)
    at l (vendor-f9cd02b2d977eb709718176b86e47f9c.js:2352:1)
    at vendor-f9cd02b2d977eb709718176b86e47f9c.js:2327:6
    at _.compile (vendor-f9cd02b2d977eb709718176b86e47f9c.js:2262:173)
    at te (vendor-f9cd02b2d977eb709718176b86e47f9c.js:2352:44)
    at vendor-f9cd02b2d977eb709718176b86e47f9c.js:2348:30
    at Z.compile (vendor-f9cd02b2d977eb709718176b86e47f9c.js:2349:23)
    at Object.evaluate (vendor-f9cd02b2d977eb709718176b86e47f9c.js:2828:224)
```

If I run `ember electron` the app launches as expected and I see the standard `<WelcomePage />` component rendered in the app window.

**Comment by rwwagner90** [comment]
@jagthedrummer if everything works with `ember electron` I suspect there is something happening with your Electron config.

I know I used to get a blank screen on Mac until I added a plist like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key>
    <true/>
    <key>com.apple.security.automation.apple-events</key>
    <true/>
  </dict>
</plist>
```

I could be totally off base here though. @bendemboski any ideas what the issue might be?

**Comment by bendemboski** [comment]
This is happening because you haven't removed the `<WelcomePage/>` component, which is put in `application.hbs` by the default new application blueprint. You'll see the same thing if you

```sh
$ ember new testproject
$ cd testproject
$ ember serve -e production
```

and then visit your dev server in a browser. This is not an issue with `ember-electron`.

**Comment by jagthedrummer** [comment]
Thanks @bendemboski, that was it!

**Comment by branscha** [comment]
I struggled with the same issue before finding this thread. It would be nice if it could be added to the quick start documentation. I suppose numerous other starters will encounter this.

**Comment by bendemboski** [comment]
@branscha the reason I didn't think this merited a PR is because as I understand it this exact issue happens in a vanilla Ember app, so whether using Ember or `ember-electron` you'll get the same behavior, and therefore doesn't seem like the job of the addon to document. That being said, I don't think it would hurt to include in our documentation somewhere (perhaps if Ember's documentation mentions it, we could mirror where/how they talk about it), so I'd definitely welcome a PR.
