### ISSUE TITLE
protocol.interceptFileProtocol is not a function

### ISSUE THREAD

**Issue by jagthedrummer** [adopted-ember-addons/ember-electron#1474]
My error tracker has reported a few instances of this error. I would assume this results in a crash for the user. All of the reported instances have been on Mac OS.

```
TypeError: protocol.interceptFileProtocol is not a function
  File "app:///src/handle-file-urls.js", line 37, col 12, in handleFileURLs
  File "app:///src/index.js", line 186, col 9, in loadApp
  File "app:///src/index.js", line 114, col 7, in App.<anonymous>
  File "node:events", line 513, col 28, in App.emit
  File "node:domain", line 489, col 12, in App.emit
  File "app:///node_modules/@sentry/electron/main/integrations/electron-breadcrumbs.js", line 119, col 20, in emitter.emit
```

https://github.com/adopted-ember-addons/ember-electron/blob/8b2940092bf329e4abca25065d1b777908b30f0d/forge/files/src/handle-file-urls.js#L37

I'm not sure what would make it so that the `interceptFileProtocol` method is missing.

**Comment by bendemboski** [comment]
The only thing I can think of is that you're calling `handleFileUrls()` before the app is ready? Is that possible? Can you verify that it's only ever being called from within an `app.on('ready', () => {})` callback or after an `await app.whenReady()` or equivalent?

**Comment by jagthedrummer** [comment]
I call `handleFileUrls` from within a `loadApp` function, and that is called in two places:

```javascript
  app.on('ready', async () => {
    ipcMain.handle('choose-folder', chooseFolder);
    loadApp();
  });

  app.on('activate', async () => {
    if (mainWindow === null) {
      loadApp();
    }
  });
```

The goal there is to handle the case where someone closes the app window without quitting the app completely, and then clicks on the app icon in the dock. Maybe somehow `activate` is happening in some cases before `ready`?

**Comment by bendemboski** [comment]
> Maybe somehow activate is happening in some cases before ready?

I don't really know, but that would be my strong suspicion. You might do some MacOS testing to confirm, but also it seems like this would be a safe change that would hopefully address it:

```ts
  app.on('ready', async () => {
    app.on('activate', async () => {
      if (mainWindow === null) {
        loadApp();
      }
    });

    ipcMain.handle('choose-folder', chooseFolder);
    loadApp();
  });
```

Although you might also consider reorganizing a bit -- as-is you could easily be calling `handleFileURLs()` multiple times and even though that may not be harmful, it's meant to be a one-time setup kind of thing. So you might consider instead:

```ts
  app.on('ready', async () => {
    ipcMain.handle('choose-folder', chooseFolder);
    doOneTimeAppSetup();
    loadApp();
  });

  app.on('activate', async () => {
    if (mainWindow === null) {
      loadApp();
    }
  });
```

where `doOneTimeAppSetup()` has pretty much all the code that the blueprint generates in `index.js` except the part that opens a `BrowserWindow` and loads the Ember app, and `loadApp()` has all that removed/moved to `doOneTimeAppSetup()`.

**Comment by jagthedrummer** [comment]
Thanks for the response on this @bendemboski. I'm sorry it took me so long to get back to it.

I think you're right that `handleFileURLs` is intended to be called only once. I was just investigating an item in my error tracker reporting this:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Failed to register protocol: file
    at c.handle (node:electron/js2c/browser_init:2:48194)
    at Object.handle (node:electron/js2c/browser_init:2:50117)
    at handleFileURLs (/Users/jgreen/projects/seshy/electron-app/src/handle-file-urls.js:39:14)
    at loadApp (/Users/jgreen/projects/seshy/electron-app/src/index.js:185:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I finally discovered that I could recreate this problem by closing the electron window without quitting, and then clicking on the icon in the dock.

I ended up leaving all of the general setup in `loadApp` and then moved all of the window management stuff into an `openAppWindow` method. So my `ready` and `activate` bits look like this:

```javascript
  app.on('ready', async () => {
    ipcMain.handle('choose-folder', chooseFolder);
    await loadApp();
    openAppWindow();
  });

  app.on('activate', async () => {
    if (mainWindow === null) {
      openAppWindow();
    }
  });
```

After making this change I haven't been able to reproduce the `Failed to register protocol: file` error. I've upgraded ember and electron since I first opened this issue, so I suspect that this new error I was investigating is more or less the new version of the error that I originally reported.

Maybe there's nothing to do here, unless `ember-electron` wanted to handle this situation out of the box. ("This situation" meaning the "close the app window without quitting and then reopen the app window when the app is re-activated" scenario.) If so, it might be nice to make similar changes to the add-on. If you're interested in that I don't mind working on a PR. If not, feel free to close this issue.

**Comment by bendemboski** [comment]
@jagthedrummer thanks for the detail! I think I'll just close this -- I'm not sure when I'll get to it, but I'm planning a significant overhaul to how `ember-electron` works to bring the Electron side more in line with `@electron/forge` and have a much thinner layer of our own doing blueprint/template setup etc.
