### ISSUE TITLE
No Ember Inspector in new app

### ISSUE THREAD

**Issue by eg271** [adopted-ember-addons/ember-electron#1697]
Install ember electron in a brand new project, Ember 5.7, ember-electron 7.0.0.

ember electron -> App opens fine with the Ember welcome page but there's no Ember Inspector visible in the Developer Tools.

If you comment out "if (app.isPackaged)" in on app ready in electron's index.js, and rerun it is visible.

But then it says Ember app not recognized

**Comment by RobbieTheWagner** [comment]
@bendemboski did Ember Inspector work with Electron ever? I forget if we ever got it working.

**Comment by jagthedrummer** [comment]
@RobbieTheWagner, yes, the inspector definitely worked previously. I recently updated my app to ember-electron 7 and just discovered that the inspector is now missing. It's super helpful and I'd love to get it back if possible.

**Comment by jagthedrummer** [comment]
I just stepped backwards through my upgrade and I found that if I _only_ update `ember-electron` itself, in my app that the inspector is still working.

But the inspector disappeared once I update all of the other packages to match the versions generated in a new app and imported all of the various config changes.

**Comment by jagthedrummer** [comment]
Found a quick fix. 😅

The conditional for this block needs to be inverted:

https://github.com/adopted-ember-addons/ember-electron/blob/c0a6c954cb7bf5a4188e8d303444c708cc1220de/forge/files/src/index.js#L34-L47

PR incoming.

**Comment by jagthedrummer** [comment]
Oh, hey, looks like you also spotted this @RobbieTheWagner : https://github.com/adopted-ember-addons/ember-electron/pull/1640#discussion_r1567572634

**Comment by eg271** [comment]
@jagthedrummer when I tried commenting out the check so that the Inspector would get installed, the Inspector says Ember app not detected.  Is this the same for you too?

**Comment by jagthedrummer** [comment]
@eg271 the inspector is working as expected for me:

![CleanShot 2024-04-17 at 13 26 04](https://github.com/adopted-ember-addons/ember-electron/assets/58702/9ac0fbf3-e8aa-4c0d-bafd-bd11a38ecf4f)

Instead of commenting out the check you might try inverting the conditional by changing `app.isPackaged` to `!app.isPackaged`.

**Comment by eg271** [comment]
the error in the console:
(node:85182) ExtensionLoadWarning: Warnings loading extension at /Users/default/Library/Application Support/electron-tst/extensions/bmdblncegkenkacieihfhpjfppoconhi:
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(Use `Electron --trace-warnings ...` to show where the warning was created)
[85182:0417/133228.753787:ERROR:extensions_browser_client.cc(68)] Extension Error:
  OTR:     false
  Level:   2
  Source:  chrome-extension://eabhdpldjggibbnnafnmbgomnaaacamj/background.js
  Message: Uncaught TypeError: Cannot read properties of undefined (reading 'onClicked')
  ID:      eabhdpldjggibbnnafnmbgomnaaacamj
  Type:    RuntimeError
  Context: chrome-extension://eabhdpldjggibbnnafnmbgomnaaacamj/background.js
  Stack Trace: 
    {
      Line:     93
      Column:   1
      URL:      chrome-extension://eabhdpldjggibbnnafnmbgomnaaacamj/background.js
      Function: (anonymous function)
    }
[85182:0417/133228.753895:ERROR:extensions_browser_client.cc(68)] Extension Error:
  OTR:     false
  Level:   1
  Source:  manifest.json
  Message: Service worker registration failed. Status code: 15
  ID:      eabhdpldjggibbnnafnmbgomnaaacamj
  Type:    ManifestError

**Comment by jagthedrummer** [comment]
I think this issue is only partially complete. There's still the issue that in a fresh app the inspector doesn't recognize that there's an ember app.

**Comment by bendemboski** [comment]
@jagthedrummer if you have time, could you see if using [electron-extension-installer](https://github.com/jonluca/electron-extension-installer) instead of `electron-devtools-installer` works? In my project we switched to that because of something I didn't think affected most apps (we use ES modules in the main process), but I'm wondering if it will fix whatever new issue you've uncovered.

**Comment by jagthedrummer** [comment]
Yep, switching to `electron-extension-installer` instead of `electron-devtools-installer` did the trick!

![CleanShot 2024-04-17 at 15 43 39](https://github.com/adopted-ember-addons/ember-electron/assets/58702/90802861-dab3-42a1-800f-54eb641e1572)

**Comment by bendemboski** [comment]
@jagthedrummer awesome, thanks for confirming that. I've updated the blueprint to make the switch.

Thanks a lot for reporting this issue, and providing all the extra detail!
