### ISSUE TITLE
Migrate PackageTask from `quickTemp` to `tmp`

### ISSUE THREAD

**Issue by anulman** [adopted-ember-addons/ember-electron#292]
In conversation on #291, @bendemboski noted a deficiency in `PackageTask`'s use of `quickTemp`.

An effort was made to migrate from `quickTemp` to `tmp` as part of that PR, but [fs permissions issues proved blocking](https://github.com/felixrieseberg/ember-electron/pull/291#discussion_r132772038) to shipping an expedient fix.

A future version of this project should migrate from `quickTemp` to `tmp`. This issue exists for tracking purposes, + in case a helpful e-electron user is looking for inspiration re: helpful contributions.

**Comment by bendemboski** [comment]
In `ember-electron` v3 there is no more assemble stage, so this is no longer an issue.
