### ISSUE TITLE
build error - path escaping

### ISSUE THREAD

**Issue by ltagliamonte** [adopted-ember-addons/ember-electron#315]
Running the build on my Jenkins I found the following issue:
```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `chmod a+x /home/ec2-user/workspace/build_on_jenkins/slaves/builder-backend-j8 (i-0f0f9451fc45dca39)/tmp/package_task-tmp_path-xulvwEAh.tmp'
```
it seems that there is an error here: https://github.com/felixrieseberg/ember-electron/blob/master/lib/tasks/package.js#L31

`projectPath`should be escaped for spaces and `()`.

**Comment by bendemboski** [comment]
This could be fixed on its own, but will also be fixed by #292 which will obviate the need for this `chmod`.

**Comment by anulman** [comment]
@ltagliamonte Following up on @bendemboski's comment, are you okay if we close this and focus on #292 in the coming sprint?

**Comment by bendemboski** [comment]
This code no longer exists is `ember-electron` v3
