### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by anulman** [adopted-ember-addons/ember-electron#328]
Per @ibrahimab's note on #324, e-electron docs are useful but do not do a great job indicating where to look upstream for valid config options / debug support.

We should take a look at documentation and make sure at least the following are covered:

### README.md
- Quickstart
- What is electron-forge?
- Basic info re devtron

### Docs dir (+ site?)
- Per-command documentation
- Common configuration options / settings
- Detailed debugging instructions
- File structure
- ASAR handling (per #242)

### Misc
- Consider CONTRIBUTING.md + issues template?

**Comment by jacobq** [comment]
Ref #404 

@rwwagner90 If you have other ideas about how to improve the docs perhaps this would be a good place to discuss. Sadly things have gotten pretty stale :/

**Comment by bendemboski** [comment]
Documentation refreshed in v3. If there are still issues, please open new issues.
