### ISSUE TITLE
ember-inspector 3.2.0 doesn't seem to work in electron

### ISSUE THREAD

**Issue by jacobq** [adopted-ember-addons/ember-electron#359]
I'm not sure how exactly we touch ember-inspector or why it would be different in electron than Chrome, but it seems pretty broken on my app right now (using [d47826](https://github.com/felixrieseberg/ember-electron/commit/d47826b3b4f9cad3d5797eee244339af35385e2d) of `ember-electron` -- not sure if it's broken prior).

Some of the problems:
* Clicking on store items in 'Data' does not show any results (though the `(xx)` count is correct)
  Note: it's almost as if the contents were being displayed in white because when I click where the items would be I can see the panel on the right side change.
* Clicking on "Info" show blank pane
* Clicking on "Routes" does not display anything

"Components" view appears to work though.

**Comment by jacobq** [comment]
BTW, this seems to be intermittent for me. Lately it's been working, though not albeit reliably.

**Comment by Mithrilhall** [comment]
I'm having issue with ember-inspector as well. When clicking 'View Tree' I get the following error:

```
Uncaught TypeError: Cannot read property 'outlets' of undefined
    at _default.getApplicationOutlet (<anonymous>:1593:42)
    at _default.buildOutletTree (<anonymous>:1367:51)
    at _default.build (<anonymous>:1341:33)
    at Class.viewTree (<anonymous>:4686:33)
    at <anonymous>:4658:27
    at invoke (backburner.js:207)
    at Queue.flush (backburner.js:125)
    at DeferredActionQueues.flush (backburner.js:278)
    at Backburner.end (backburner.js:410)
    at Backburner._runExpiredTimers (backburner.js:831)
getApplicationOutlet @ VM161:1593
buildOutletTree @ VM161:1367
build @ VM161:1341
viewTree @ VM161:4686
(anonymous) @ VM161:4658
invoke @ backburner.js:207
flush @ backburner.js:125
flush @ backburner.js:278
end @ backburner.js:410
_runExpiredTimers @ backburner.js:831
Backburner._boundRunExpiredTimers @ backburner.js:368
setTimeout (async)
Backburner.platform.setTimeout @ backburner.js:354
_installTimerTimeout @ backburner.js:876
_setTimeout @ backburner.js:778
later @ backburner.js:566
run.later @ ember-metal.js:681
scheduledSendTree @ VM161:4653
invoke @ backburner.js:205
flush @ backburner.js:125
flush @ backburner.js:278
end @ backburner.js:410
_run @ backburner.js:760
run @ backburner.js:468
run @ ember-metal.js:408
wrap @ VM161:3631
messageReceived @ VM161:3602
(anonymous) @ VM161:3594
(anonymous) @ VM161:131
_messageReceived @ VM161:130
(anonymous) @ VM161:324
_run @ backburner.js:758
run @ backburner.js:468
run @ ember-metal.js:408
(anonymous) @ VM161:323
```

**Comment by jacobq** [comment]
@Mithrilhall Weird -- that sounds like it could also be something related to your app code. Can you repro in a minimal app (e.g. `ember new repro-app; cd repro-app; ember install ember-electron; ember electron`)?

**Comment by Mithrilhall** [comment]
Sure. I'll give it a shot and I'll post back.

**Comment by Mithrilhall** [comment]
Steps I took:

1. `ember new repro-app`
2. `cd repro-app`
3. `ember install ember-electron`
4. Edit `repro-app/ember-electron/main.js'` and uncomment `mainWindow.openDevTools();`
5. `ember electron`
6. Click the `Ember` tab in dev-tools and get the following error:

```
VM141:1593 Uncaught TypeError: Cannot read property 'outlets' of undefined
    at _default.getApplicationOutlet (<anonymous>:1593:42)
    at _default.buildOutletTree (<anonymous>:1367:51)
    at _default.build (<anonymous>:1341:33)
    at Class.viewTree (<anonymous>:4686:33)
    at <anonymous>:4658:27
    at invoke (backburner.js:249)
    at Queue.flush (backburner.js:167)
    at DeferredActionQueues.flush (backburner.js:326)
    at Backburner._end (backburner.js:772)
    at Backburner.end (backburner.js:514)
```

Additional Information:
```
$ ember -v
ember-cli: 3.2.0
node: 8.11.3
os: linux x64
```

**Comment by jacobq** [comment]
Thanks -- that should be helpful for figuring out what's going on. (I assume you're using `ember-electron` v2.8.0 [I've been using `master` since there hasn't been a release yet since #355 landed], and that this does not occur when not using electron.)

**Comment by Mithrilhall** [comment]
I'm using v2.8.0 indeed.

**Comment by jacobq** [comment]
@pboutin Can you reproduce the problem? Any information you can provide may be helpful. It hasn't caused me much trouble lately, and when it has I've been able to resolve it by closing the dev tools, opening them again, and refreshing the page. :man_shrugging:

**Comment by pboutin** [comment]
I tried again yesterday and it worked 🤷‍♂️ . I will try to keep an eye open for this...

**Comment by Mithrilhall** [comment]
Just tried a new project and I'm still having issues with it.

```
ember -v
ember-cli: 3.5.1
node: 8.14.0
os: linux x64
```
Partial package.json
```
"ember-electron": "^2.10.0",
"devtron": "^1.4.0",
"electron-forge": "^5.2.3",
"electron-prebuilt-compile": "3.0.10",
```

![image](https://user-images.githubusercontent.com/5432148/49594273-80925980-f943-11e8-8360-727b16773559.png)

**Comment by jacobq** [comment]
> Just tried a new project and I'm still having issues with it.

I occasionally encounter that problem too. Does the magic incantation (click another tab, refresh, open/close dev tools, click Ember inspector tab again) "fix it" or does it happen every time?

**Comment by bendemboski** [comment]
This will be fixed once [this PR](https://github.com/emberjs/ember-inspector/pull/1084) in `ember-inspector` is released.

**Comment by rwwagner90** [comment]
I'm not seeing Devtron or Ember Inspector showing up in my DevTools anymore. Are you guys still seeing them on the latest ember-electron beta?

**Comment by bendemboski** [comment]
I broke them in one of the later commits in my PR. I have a fix, just want to figure out how to write a test for it, and also think about whether there's a reasonable way to install the ember inspector from the main process so it can still be installed in windows with node integration disabled.

**Comment by rwwagner90** [comment]
@bendemboski sounds good, just wanted to make sure I didn't break anything. When do you think we could get that fix in?

**Comment by bendemboski** [comment]
Should be able to get it in today, without the node integration disabled
part. Will need to think about that some more.

**Comment by jacobq** [comment]
I don't know whether to this is caused by something else or what, but with electron 8 I can't use the ember inspector at all. Repro here: https://github.com/jacobq/ember-electron-inspector-bug-repro Works fine with electron 7.1.12

**Comment by rwwagner90** [comment]
@jacobq it's been broken for me even pre-8. Opening inspector crashes my app. Haven't looked into why yet.

**Comment by rwwagner90** [comment]
Inspector works again in Electron 11.3.0. They had to add options for allowing file extensions https://github.com/electron/electron/releases/tag/v11.3.0
