### ISSUE TITLE
TODO: Improve CodeClimate scores

### ISSUE THREAD

**Issue by jacobq** [adopted-ember-addons/ember-electron#369]
This might not seem like a big deal, but our current score of "D" makes this project seem in worse shape than it actually is. It [looks like](https://codeclimate.com/github/felixrieseberg/ember-electron/issues?severity%5B%5D=major&category%5B%5D=complexity&category%5B%5D=duplication&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=structure&engine_name%5B%5D=duplication) there are a number of cases where all we need to do to improve the rating is reduce some duplication or shorten a function by a few lines.

**Comment by bendemboski** [comment]
@jacobq I reran this on the latest, and the score is a C now, with most of the issues being code repetition in tests, and a few too-long functions. I personally disagree that core repetition in tests is automatically a bad thing, and am happy to discuss if you're interested.

I also don't think the functions that are longer than the 25 line limit are difficult to read or to maintain.

So I guess I'm saying that I don't think it's actually giving us any valuable insights into how to make our code more maintainable, and I'm not really interested in arbitrarily refactoring code to improve the score.

Do you object to closing out this issue?

**Comment by rwwagner90** [comment]
@bendemboski I'm going to add a config to tweak some settings. Hopefully that should help.

**Comment by jacobq** [comment]
> Do you object to closing out this issue?

Not at all. I was just going to suggest that if we're not going to seek to improve the score then we should take the badge off the README :) 

Thanks for "fixing" this @rwwagner90 ;)
