### ISSUE TITLE
Unable to disable the live reload

### ISSUE THREAD

**Issue by dev-zetta** [adopted-ember-addons/ember-electron#375]
How to disable the live reload feature?

Setting the 'DO_NOT_SETUP_LIVERELOAD' flag does disable the live reload.
I also have '"liveReload" : false' set in the .ember-cli. Still not working.

Tested on latest version of ember-electron and ember-cli.

Edit: I also tried setting the '--liveReload=false', but ember electron seems ignoring this flag.

**Comment by jacobq** [comment]
Hmm, I hadn't tried this before but did just now on my linux box by running the following, and it worked fine:
```
$ DO_NOT_SETUP_LIVERELOAD=1 ember electron
```
When I make a change to, say, a controller's source code, and save the file then I see the build update on the console but the application does not refresh. When I close the app and run again without that environment variable changing that file again does trigger a refresh, as expected.

I don't see anything wrong with the [line that checks for this condition](https://github.com/felixrieseberg/ember-electron/blob/dd9227aa5913e46658718b40143f6630edab996e/app/electron/reload.js#L5), do you? What platform are you using? How are you "setting the flag"? What does `process.env` show?

![process.env in dev tools shows DO_NOT_SETUP_LIVERELOAD=1](https://user-images.githubusercontent.com/1633459/47792512-2ff76300-dcea-11e8-9cdb-4e718c52d4ac.png)

**Comment by dev-zetta** [comment]
Thank you for the help.

I had 'DO_NOT_SETUP_LIVERELOAD=true' added in the command and in the ember-cli-build.js, but setting it to integer instead of boolean  (i.e. 1 instead of true) helped. It should however check only for presence of DO_NOT_SETUP_LIVERELOAD flag, not the type or its value. 

Now it works... however, why doesn't setting the '"liveReload" : false' disable the live reload?

**Comment by jacobq** [comment]
@dev-zetta 

1. To what does `process.env.DO_NOT_SETUP_LIVERELOAD` evaluate in the dev tools' console when you have "DO_NOT_SETUP_LIVERELOAD=true in the command"? I think you will find that it didn't get defined for some reason (typo?). The referenced `ember-electron` code doesn't check type or value, only "truthiness" in the JS sense so it's very likely that there was something else going on in the case you described, but it's not possible to know for certain without more information.
```sh
$ myVar=foo node -e 'console.log(!!process.env.myVar)' # output: true
```

2. I'm not sure about the `.ember-cli` settings and have never tried to use it. Perhaps it was [only added recently](https://github.com/ember-cli/ember-cli/commit/c584c7fc45a3ac9228a3aadade23dc4b6670b0e5)? Perhaps `ember-electron` is [using an old version of `ember-cli-inject-live-reload`](https://github.com/felixrieseberg/ember-electron/blob/a34780998adadbbdc888e1b4c2706f965e365585/package.json#L97)? (if so, PR #358 should help)

3. Where are the docs for `--liveReload=false` option? (Did you just invent that or did you read it somewhere? I am not familiar with this)

Ref https://github.com/felixrieseberg/ember-electron/issues/263

**Comment by bendemboski** [comment]
`ember electron --live-reload=false` is not supported in `ember-electron` v3 (currently in beta)
