### ISSUE TITLE
Installs electron-prebuilt-compile 4.0.0 by default, which fails ember electron:make -prod

### ISSUE THREAD

**Issue by DanLeininger** [adopted-ember-addons/ember-electron#384]
A fresh install, with ember-cli 3.8.1:

```
ember new my-project
ember install ember-electron
```

Installs 

```
"electron-prebuilt-compile": "4.0.0",
```

Which then causes 

```
ember electron:make -prod
```

To fail with 

```
ENOENT: no such file or directory, open '/var/folders/pq/3zy6j6_n3hz_1wkgdxznzbz40000gq/T/electron-packager/darwin-x64/MyProject-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist'


Stack Trace and Error Report: /var/folders/pq/3zy6j6_n3hz_1wkgdxznzbz40000gq/T/error.dump.a7eaaf95c3da4f49ad047b0700e67651.log
``` 

This will build if you downgrade electron-prebuilt-compile to the latest 3.0.x

```
"electron-prebuilt-compile": "3.0.13",
```

**Comment by jacobq** [comment]
@DanLeininger Thanks for pointing this out. Maybe we should pin it until https://github.com/electron-userland/electron-prebuilt-compile/issues/77 is resolved. I wish so much that epc had automatic releases or that ef would work easily with forks.

**Comment by rwwagner90** [comment]
This should be fixed with the updates to electron-forge we just merged in https://github.com/adopted-ember-addons/ember-electron/pull/418

**Comment by rwwagner90** [comment]
@bendemboski should we close this now that v3 beta is out?
