### ISSUE TITLE
How to build with custom `electron-prebuilt-compile`

### ISSUE THREAD

**Issue by jacobq** [adopted-ember-addons/ember-electron#388]
Anyone get `ember-electron` to successfully package an app while using an unofficial version of [`electron-prebuilt-compile`](https://github.com/electron-userland/electron-prebuilt-compile) (e.g. to use v4.1.4)? I am [using a tarball URL](https://github.com/electron-userland/electron-prebuilt-compile/issues/77#issuecomment-480881828), and it almost works. I can run `ember electron` fine, but when I try to package (`ember electron:make ...`) I run into problems.

Part of it is because `electron-packager` (v11 used by `electron-forge` v5.2.4 used by current `ember-electron`) expects `electron-prebuilt-compile` to be specified as a version string (see https://github.com/electron-userland/electron-packager/issues/975). However, even when I fork `electron-forge` and `electron-packager` to correct for this, I now get an unexpected `Failed to locate module` error for things that should just be devDependencies, e.g.:

```
cleaning up...
Built and assembled Electron project successfully. Stored in "/path/to/app/tmp/package_task-tmp_path-n3SsStVQ.tmp".
Packaging Electron project.
Failed to locate module "@types/ember" from "/path/to/app/tmp/package_task-tmp_path-n3SsStVQ.tmp"

        This normally means that either you have deleted this package already somehow (check your ignore settings if using electron-packager).  Or your module installation failed.


Stack Trace and Error Report: ...
```

**Comment by jacobq** [comment]
I can "work around" this by setting `electronPackager: { prune: false, ... }` in `electron-forge-config.js`, but I've never had to do that before and don't understand why I would now. What part of the code is trying to lookup a module like `@types/...` / how can I tell / why is it doing that?

**Comment by rwwagner90** [comment]
@bendemboski should we close this now that v3 beta is out?

**Comment by bendemboski** [comment]
In the 3.0 beta we're on the latest electron-forge which doesn't use `electron-prebuilt-compile` 🎉
