### ISSUE TITLE
@action decorator missing

### ISSUE THREAD

**Issue by dev-zetta** [adopted-ember-addons/ember-electron#394]
Hello everyone,

after upgrading ember-electron and ember-decorators to new versions, I cannot compile my code, because there is missing export for @action decorator from ember object.

```js
import { action } from '@ember/object'

class MyClass extends Component {
  @action
  myAction() {
    // ...
  }
}
```

It reports error ReferenceError: action is not defined.

Using ember-electron v2.10.0. When I remove the decorator, to make it compile, the action is not found.

Any ideas? It seems that ember-electron is using outdated ember packages, or am I wrong?

**Comment by jacobq** [comment]
> Any ideas? It seems that ember-electron is using outdated ember packages, or am I wrong?

I know the version published on npm is quite out of date. Maybe I need to work with @Alonski and @bendemboski to figure out what the new (post-adoption) release process is. (Then I need to retry the "upgrade deps" PR I attempted about a year ago then forgot about to get us back into the modern world.) In the meantime, here's an excerpt from my `package.json`, which has been working fine w/ decorators, typescript, ember 3.10,
 etc.:

```json
  "devDependencies": {
    "electron-prebuilt-compile": "https://registry.npmjs.org/@jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-5.0.1.tgz",
  },
  "dependencies": {
    "ember-electron": "adopted-ember-addons/ember-electron#34d20f76a3ee3e58e2bbbb5452cc48d9e1fa2983",
  },
  "resolutions": {
    "**/broccoli-postcss": "^4.0.1",
    "**/electron-forge": "https://registry.npmjs.org/@jacobq/electron-forge/-/electron-forge-5.2.4-jrq.6.tgz",
    "**/electron-packager": "electron-userland/electron-packager#7182f9080328dbef79538d384e54c597e103bd32",
    "**/node-abi": "jacobq/node-abi#15baa5fa42a4a379b182d08075f0515a8e9460ec"
  },
```

**Comment by Alonski** [comment]
Hey @jacobq, I don't use this addon, so I don't know how much say I have :)

However it seems that you have permissions on NPM to cut releases to NPM. I say if you have time to create an upgrade PR that would be awesome :)

I really love this technique:
https://embermap.com/video/how-to-upgrade-an-ember-app-or-addon

**Comment by jacobq** [comment]
@dev-zetta FWIW, I was able to get it working just now w/o any of that. Not sure what's different in my [test/repo app](https://github.com/jacobq/ee-action-test).

**Comment by jacobq** [comment]
> Hey @jacobq, I don't use this addon, so I don't know how much say I have :)

I just remember seeing your name on the email thread regarding adoption, so figured you were "in the know" :D 

> However it seems that you have permissions on NPM to cut releases to NPM. I say if you have time to create an upgrade PR that would be awesome :)

Interesting, I never tried to `npm publish` and would be willing to try that in the mean time. However, @felixrieseberg had done some work to setup a semantic-release bot, and I'd like to learn more about how that works / is supposed to work first.

> I really love this technique:
> https://embermap.com/video/how-to-upgrade-an-ember-app-or-addon

I do too, though I tend to be more aggressive (e.g. `ember-cli-update`, resolve conflicts, `ncu -u && yarn upgrade`) when the stakes are low.

**Comment by Alonski** [comment]
@jacobq Yea just saw that semantic release thing.
So I am definitely "in the know" I orchestrated the whole adoption :)

However, I did it so that the community could benefit. 
If you need any more help I am here to help out :)

BTW could you take a quick crack at this: #393

**Comment by dev-zetta** [comment]
> > Any ideas? It seems that ember-electron is using outdated ember packages, or am I wrong?
> 
> I know the version published on npm is quite out of date. Maybe I need to work with @Alonski and @bendemboski to figure out what the new (post-adoption) release process is. (Then I need to retry the "upgrade deps" PR I attempted about a year ago then forgot about to get us back into the modern world.) In the meantime, here's an excerpt from my `package.json`, which has been working fine w/ decorators, typescript, ember 3.10, etc.:
> 
> ```json
>   "devDependencies": {
>     "electron-prebuilt-compile": "https://registry.npmjs.org/@jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-5.0.1.tgz",
>   },
>   "dependencies": {
>     "ember-electron": "adopted-ember-addons/ember-electron#34d20f76a3ee3e58e2bbbb5452cc48d9e1fa2983",
>   },
>   "resolutions": {
>     "**/broccoli-postcss": "^4.0.1",
>     "**/electron-forge": "https://registry.npmjs.org/@jacobq/electron-forge/-/electron-forge-5.2.4-jrq.6.tgz",
>     "**/electron-packager": "electron-userland/electron-packager#7182f9080328dbef79538d384e54c597e103bd32",
>     "**/node-abi": "jacobq/node-abi#15baa5fa42a4a379b182d08075f0515a8e9460ec"
>   },
> ```

I checked your repo and compared. It looks almost identical, no fancy changes. I tried to use update my package.json with those new deps, everything installed fine, but after I start the app, it throws me an error:
`Missing npm packages: 
Package: electron-prebuilt-compile
  * Specified: https://registry.npmjs.org/@jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-5.0.1.tgz
  * Installed: jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-5.0.1.tgz

Run `npm install` to install missing dependencies.
`

**Comment by jacobq** [comment]
> Missing npm packages:
> Package: electron-prebuilt-compile
> 
> * Specified: https://registry.npmjs.org/@jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-5.0.1.tgz
> * Installed: jacobq/electron-prebuilt-compile/-/electron-prebuilt-compile-5.0.1.tgz
> 
> Run `npm install` to install missing dependencies.

That sounds like either an npm/yarn cache problem or something either ember-cli-dependency-checker. What happens if you nombom or use epc `3.0.13` (latest 3.x version that was published by the original author) instead of my fork?

**Comment by jacobq** [comment]
> I checked your repo and compared. 

@dev-zetta Did you try running it? Did it work? (It definitely works on my machine)

**Comment by dev-zetta** [comment]
@jacobq Thank you for those tips. No matter what I have tried, the error still occurs. I copied exact version number for each package from your repo, checked configuration, etc. Still same error.

I tried to run your example and it works as expected. I have the same config as you do, plus some other ember plugins.

Here is a snipped from the debug console:
```
DEBUG: -------------------------------
vendor.js:51708 DEBUG: Ember           : 3.10.0
vendor.js:51708 DEBUG: Ember Data      : 3.10.0
vendor.js:51708 DEBUG: jQuery          : 3.4.1
vendor.js:51708 DEBUG: Ember Bootstrap : 2.7.0
vendor.js:51708 DEBUG: Model Fragments : 4.0.0
vendor.js:51708 DEBUG: -------------------------------
```
And here is my package.json: https://gist.github.com/dev-zetta/c749c024676b09e6d9522c123304a6bf

Could you please have a look? If I have something wrong there?

**Comment by Alonski** [comment]
@dev-zetta Are you using a lock file? Maybe try pinning dependencies to the exact version specified by the working branch in their lock file?

**Comment by dev-zetta** [comment]
I found source of this bug. It's caused by ember-cli, not ember-electron. So I'm closing this issue and I'll report it over there.
