### ISSUE TITLE
ember-electron:package seems to ignore `make_targets`

### ISSUE THREAD

**Issue by cupofnestor** [adopted-ember-addons/ember-electron#398]
I am having trouble building .deb ( .rpm, snap) packages on a native linux box.

## Expected Behavior
`ember electron:package` generates linux .deb or snap packages based on values of `make_targets` in `ember-electron/electron-forge-config.js`

## Current Behavior
`ember electron:package` seemingly ignores `ember-electron/electron-forge-config.js` and generates `electron-out/project-name-linux-x64` directory containing scripts and resources, but no packages

## Steps to Reproduce

1.  `ember new project-name`
2.  `cd project-name && ember install ember-electron`
3.  `ember electron:package` 

## Context
```
ember-cli: 3.10.1
node: 10.16.0
os: linux x64
```
electron-forge-config.js:
``` javascript
"make_targets": {
   "linux":[
      "deb","rpm"
   ]
}
```

**Comment by bendemboski** [comment]
I believe you're misunderstanding the commands. `electron:package` creates an executable application that you can run directly. `electron:make`, which I think is what you want, creates a distributable installer according to the `make_targets`. See https://ember-electron.js.org/ for a description of the various commands and what they do.

If I'm misunderstanding something here, feel free to re-open.
