### ISSUE TITLE
ember electron {make, package} fails on darwin builds

### ISSUE THREAD

**Issue by cupofnestor** [adopted-ember-addons/ember-electron#399]
Relevant:

https://github.com/electron/electron-packager/issues/927
https://github.com/adopted-ember-addons/ember-electron/issues/384

We are having the same trouble as these folks.  Here is what I've tried:

- [x]  `npm install electron-packager@11.2.1`
❌ `:make` fails
- [x]  `npm update ember-electron`
❌ `:make` fails
- [x] `npm r electron-prebuilt-compile && npm i --save-dev electron-prebuilt-compile@3.0.13`
✅ `:make` succeeds

Why do we need to downgrade `prebuilt-compile`, whose dep is this?  
What is the best course of action to support my devs?  - modify package.json in the ember project to v3.0.13?

**Comment by jacobq** [comment]
Although I don't have easy access to Mac machines to test, I suspect this is related to the problems (e.g. [see this comment](https://github.com/electron-userland/electron-prebuilt-compile/issues/77#issuecomment-480881828)) I've had that mostly boil down to (1) [`electron-prebuilt-compile`](https://github.com/electron-userland/electron-prebuilt-compile) (required by electron-forge v5.x) being abandoned and (2) [`electron-forge`](https://github.com/electron-userland/electron-forge) v6.0.0 not being released yet. If downgrading solves your problem for now then that is probably the most expedient "solution". However, what I think we (users/contributors to `ember-electron`) really need to do is to update the codebase to use electron-forge 6 (beta). That should help break some long-standing log-jams.

**Comment by rwwagner90** [comment]
@jacobq I believe this should be fixed with the electron-forge updates right?

**Comment by rwwagner90** [comment]
@bendemboski should we close this now that v3 beta is out?

**Comment by bendemboski** [comment]
In the 3.0 beta we're on the latest `electron-forge` and `electron-packager`. If you update and it's still happen, feel free to reopen or open a new issue with updating info.
