### ISSUE TITLE
Failed to update .travis.yml on new/empty project

### ISSUE THREAD

**Issue by jacobq** [adopted-ember-addons/ember-electron#429]
Attempting to run 3.0.0-beta.0 on a new/empty Ember app results in an error/warning like this:

```
Updating .travis.yml
Failed to update .travis.yml. For info on manually updating your CI config read https://adopted-ember-addons.github.io/ember-electron/docs/guides/ci.
Error: TypeError: Cannot read property 'includes' of undefined
```

I think this because the [default `.travis.yml`](https://github.com/ember-cli/ember-new-output/blob/master/.travis.yml) does not have an `install` section, so the following line reduces to `let entry = [].find(...) || [].find(...)` which is `undefined`.

https://github.com/adopted-ember-addons/ember-electron/blob/a6dd363edbf2d53f5b300502912ad04051ab5f48/blueprints/ember-electron/index.js#L87

**Comment by jacobq** [comment]
Seems like we could easily detect this and at least make the message more meaningful. E.g. "TravisCI configuration file does not appear to have an 'install' section, so this was not updated. Refer to ..."

**Comment by rwwagner90** [comment]
@jacobq how is there no install section? Doesn't the ember default include install?

**Comment by rwwagner90** [comment]
Weird, you are correct it does not have install. How do tests ever pass without installing deps?

**Comment by bendemboski** [comment]
`yarn` vs. `npm` https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/.travis.yml#L26-L33

**Comment by bendemboski** [comment]
Maybe the default `install` section if not overridden is to `npm install`? This hidden magic is why I think CircleCI is way better than Travis these days...

**Comment by rwwagner90** [comment]
That could be, but I would think Ember would include it either way. I am surprised they opted not to.

**Comment by jacobq** [comment]
> Maybe the default `install` section if not overridden is to `npm install`?

Yes, if language is `node_js` [default install is `npm install or npm ci`](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/). 

> This hidden magic is why I think CircleCI is way better than Travis these days...

I've not used CircleCI so can't judge, but it doesn't seem fair to call having a reasonable, documented default "hidden magic" :).

Perhaps our script should add the default `install` entry, if it's not already present, and then modify it as if it had been there explicitly.

**Comment by rwwagner90** [comment]
@jacobq I would advocate that we should open a PR to Ember and add a default install for npm, even though it's not technically needed.

**Comment by jacobq** [comment]
> @jacobq I would advocate that we should open a PR to Ember and add a default install for npm, even though it's not technically needed.

:man_shrugging: I'm not opposed to that, but then (1) it needless affects people not using this addon and (2) it doesn't help people using apps created with older ember-cli versions.

**Comment by rwwagner90** [comment]
@jacobq I do think that either way we should check for the existence of install and if it is not there, add one.
