### ISSUE TITLE
Issues with electron-forge versions

### ISSUE THREAD

**Issue by rwwagner90** [adopted-ember-addons/ember-electron#431]
I ran a `yarn upgrade` in my ember project, and unknowingly broke my build, since electron-forge is bundled with ember-electron, and had just released a new version. I spoke to @bendemboski about it a bit, and he has some ideas to try to consolidate versions of electron-forge. We'll need to figure out a solution, so this does not happen in the future.

**Comment by bendemboski** [comment]
We need to figure out what to do about dueling electron-forge versions (the one that is a dependency of `ember-electron` and the one that gets installed in `electron/app`)
