### ISSUE TITLE
No run in ember-electron v3

### ISSUE THREAD

**Issue by debelop13** [adopted-ember-addons/ember-electron#441]
Hi,

I am migrating to v2 to v3 following these steps: https://ember-electron.js.org/versions/v3.0.0-beta.1/docs/guides/upgrading

I was fixing different errors, but now i am blocked because when I run "ember electron" it is stopped without any error

This is the log:

> Checking dependencies in electron-app...
DEPRECATION: The integration of jQuery into Ember has been deprecated and will be removed with Ember 4.0. You can either opt-out of using jQuery, or install the `@ember/jquery` addon to provide the jQuery integration. Please consult the deprecation guide for further details: https://emberjs.com/deprecations/v3.x#toc_jquery-apis
Environment: development

> Build successful (9232ms)

> Slowest Nodes (totalTime => 5% )              | Total (avg)         
----------------------------------------------+---------------------
Babel: @ember-data/adapter (2)                | 1613ms (806 ms)     
Package /assets/vendor.js (1)                 | 907ms               
Babel: ember-lodash (1)                       | 880ms               
BroccoliRollup (5)                            | 819ms (163 ms)      
Babel: ember-load-initializers (1)            | 749ms               
Babel: ember-basic-dropdown (2)               | 666ms (333 ms)      

> Starting Electron...
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
[11:13:40.823] [info] Disabling hardware accleration...
(node:79319) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:79319) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:79319) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(node:79319) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
cleaning up...

There are any project v3 example to compare and know where is the error?

Thanks!

**Comment by rwwagner90** [comment]
I am using v3 with no issues. It sounds like maybe some of your electron packages might not be compatible with newer electron, but I am not sure.

**Comment by debelop13** [comment]
Maybe, if I run the auto generated index.js it runs, but my old index.js (main.js) no

I will try disabling packages

**Comment by jacobq** [comment]
> I was fixing different errors, but now i am blocked because when I run "ember electron" it is stopped with any error

I only see deprecation warnings in the log, not fatal errors. If you can share a simple repo that demonstrates the problem I will take a look.

**Comment by debelop13** [comment]
Sorry, without any error, yes.

I didn't see erros with `DEBUG=*electron* ember electron` or `DEBUG=*,-*babel ember electron`

> 16:53:43.246 › Disabling hardware accleration...
> (node:5635) DeprecationWarning: file property is deprecated and will be removed in v5.
> (node:5635) DeprecationWarning: file property is deprecated and will be removed in v5.
> 16:53:43.523 › createWindow
> 16:53:43.532 › createWindow2
> (node:5635) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
> (node:5635) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
>   ember-electron:electron-task Electron exited. +0ms
>   ember-electron:electron-task Electron closed with code: 0 with signal: null +1ms
> cleaning up...

But I see that  for some reason electron is being closed

**Comment by jacobq** [comment]
> But I see that for some reason electron is being closed

Sounds like you're on the right track. Sorry I can't be more helpful without seeing the problem for myself. My suggestion would be to add more debug logging, exception handling, etc. to your main thread code or try something like the ["quick start" app](https://github.com/electron/electron-quick-start) (e.g. create a new/empty ember app, install this addon, and try to reproduce the behavior).

**Comment by rwwagner90** [comment]
I know I had a lot of packages that did not support latest node and electron and had to fix some things. I would bet that is what is happening here. Also, you'll have to update your index.js. Just using the old one is probably not going to work out of the box.

**Comment by bendemboski** [comment]
A couple of quick tips:

1. I highly recommend upgrading `ember-electron` without upgrading your `Electron` version first, getting that working, then upgrading `Electron`.
2. After running `ember electron` once, the Ember app will be built into `electron-app/ember-dist`, so if you're just working on/debugging main process stuff, you can `cd electron-app` and `yarn start` to just launch your Electron app, picking up any changes you made to files in `electron-app/`, but not rebuilding the Ember app. This can speed up your dev cycle quite a bit.
3. I *think* you can try something like `app.on('before-quit', () => console.log('quitting', new Error()));`, and if something is quitting the Electron app using `app.exit()` (don't think it will pick up `process.exit()` I believe this will print a stack trace pointing back to whoever called `app.exit()`, but if something else is causing the app to exit, this might not help. But an easy experiment to try!

**Comment by bendemboski** [comment]
@debelop13 I'm going to close this issue as it's currently really a support request, and is not an actionable issue with `ember-electron`. Feel free to continue the support discussion on this issue, or, better yet, ask in the #topic-desktop channel of Ember Discord, which is set up for these sort of support requests/discussions.

**Comment by debelop13** [comment]
Okey, the exiting was because I was using the new `app.requestSingleInstanceLock()` instead of old `app.makeSingletonInstance` but not correctly.
 
Now this works, thanks to everyone.
