### ISSUE TITLE
Source maps not loading with Electron 7.x

### ISSUE THREAD

**Issue by bendemboski** [adopted-ember-addons/ember-electron#442]
When running `ember electron` with Electron 7.x, if you open the dev tools, the source maps do not load.

The root cause is changes in Chromium around the network service. Things broke in Electron 7.0.0, and [this](https://github.com/electron/electron/pull/21494) fix (a backport of [this](https://chromium-review.googlesource.com/c/chromium/src/+/1525270) chromium fix) got source maps working again for `file:` URLs. But they still don't work for custom protocols, like our `serve:` protocol that we use with `electron-protocol-serve`.

[Here](https://github.com/electron/electron/issues/21699) is the Electron issue I filed tracking this, but I have no idea if it will get attention/a fix anytime soon. Possible alternatives:

1. Look into a way of instrumenting the build or runtime protocol handling to rewrite the `sourceMappingURL` directive at the end of js files to use absolute `file:` URLs to point to the source maps (instead of relative URLs that end up resolving to custom protocol `serve:` URLs)
2. Toss the whole custom procotol/`electron-protocol-serve` thing, and go back to using `file:` URLs (which probably requires using the hash location type in Ember)

**Comment by jacobq** [comment]
I was wondering what happened (thought maybe it was a problem on my side)
