### ISSUE TITLE
"requireNode" not defined in v3.0.0-beta-1

### ISSUE THREAD

**Issue by timmyomahony** [adopted-ember-addons/ember-electron#443]
I've set up a brand new repo via `ember init` and `ember install ember-electron@v3.0.0-beta1`. Everything works out of the box until I try to use `requireNode` in my Ember app to import Node functionality.

I've created a `controllers/application.js` and included:

```js
/* global requireNode, $ */
import Controller from '@ember/controller';

let electron = requireNode('electron');

export default Controller.extend({
});
```

Then run `ember electron` which builds OK. But in the DevTools I get the error:

> Error while processing route: index requireNode is not a function TypeError: requireNode is not a function

I'm using `"ember-electron": "^3.0.0-beta.1",` and my `ember --version`:

```
ember-cli: 3.15.1
node: 8.12.0
os: darwin x64
```

And here is the `electron-app/package.json`:

```
"dependencies": {
    "electron-protocol-serve": "^1.3.0",
    "electron-squirrel-startup": "^1.0.0"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.47",
    "@electron-forge/maker-deb": "^6.0.0-beta.47",
    "@electron-forge/maker-rpm": "^6.0.0-beta.47",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.47",
    "@electron-forge/maker-zip": "^6.0.0-beta.47",
    "devtron": "^1.4.0",
    "electron": "7.1.9",
    "ember-inspector": "^3.13.1"
  }
```

I notice in the DevTools that `window.requireNode` exists as a key, but is `undefined`

<img width="484" alt="Screenshot 2020-01-20 at 16 13 52" src="https://user-images.githubusercontent.com/615149/72741592-dd7cbd80-3b9f-11ea-84c6-3db53bc5de12.png">

**Comment by timmyomahony** [comment]
🍾  I fixed it. I had been seeing the warning in the console:

> ember-electron is unable to require node modules, possibly because nodeIntegration is not enabled.

You need `nodeIntegration` set in `ember-app/src/index.j`:

```
...

app.on('ready', () => {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  });

...
```

**Comment by rwwagner90** [comment]
`nodeintegration` is recently false by default in Electron. This has bitten me a few times 😬
