### ISSUE TITLE
Deprecation warnings in terminal

### ISSUE THREAD

**Issue by dtolios** [adopted-ember-addons/ember-electron#595]
```
(electron) 'setName function' is deprecated and will be removed. Please use 'name property' instead.
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
```

I'm seeing these two deprecation warnings when installing a fresh project.

**Comment by jacobq** [comment]
> I'm seeing these two deprecation warnings when installing a fresh project.

Which version are you using? (e.g. latest/2.10.2 or beta/3.0.0-beta.4?)

**Comment by dtolios** [comment]
Thanks for getting back to me. 
I was using latest/2.10.2

Do you suggest I move to the 3.0.0-beta branch?

**Comment by jacobq** [comment]
> Do you suggest I move to the 3.0.0-beta branch?

Yes, there has been a lot of work recently (thanks to Ben and Rob), so I wouldn't expect to see effort on 2.x to resolve deprecation warnings. 
Check out https://ember-electron.js.org/versions/v3.0.0-beta.3/

**Comment by dtolios** [comment]
Ok cool, that is totally fair. Thanks for the prompt responses!
