### ISSUE TITLE
Should use full path to `node` for launcher

### ISSUE THREAD

**Issue by rwjblue** [adopted-ember-addons/ember-electron#750]
https://github.com/adopted-ember-addons/ember-electron/blob/98e9237282ea572de3b490b26de0ebfc4c3eebad/lib/test-runner.js#L23

Should be:

```js
  exe: process.execPath,
```

**Comment by rwwagner90** [comment]
@rwjblue seems logical to me. Did this bite someone somewhere?

**Comment by rwjblue** [comment]
Not that I know of (though on my system I do not have a `node` in `$PATH` so it _would_ have bit me if I were using this addon)! I just noticed while perusing the code.

**Comment by rwwagner90** [comment]
@bendemboski I am fine with making this change if you are
