### ISSUE TITLE
Issue with shim loading on windows

### ISSUE THREAD

**Issue by basz** [adopted-ember-addons/ember-electron#914]
Hi, I have an issue with the loading of the shim files on windows. ON MacOS they seem to load just fine.

Because of this requireNode (and thus ipcRenderer) is not available. At least I suspect they are missing becuase of this.

The path for the shims are on PC and Mac

`file:///D:/ember-electron/shim-head.js`

`file:///ember-electron/shim-head.js`

As you can see my app is launched from an additional drive called D.

If I inspect the interceptFileProtocol method I can see other url's (that do load fine) have a completely different pattern

for example:

`file:///D:/hf-app-lab-device-utility/electron-app/ember-dist/assets/vendor.js`

I I patch ember-electron/index.js injectScript function to not use a prepending slash as url

```
-  return `<script src="/ember-electron/${scriptName}"></script>`;
+  return `<script src="ember-electron/${scriptName}"></script>`;
```

the shims paths are correctly requested and interpreted (and my ipcRenderer works again).

`file:///D:/hf-app-lab-device-utility/electron-app/ember-dist/ember-electron/shim-head.js`.

**Comment by evoactivity** [comment]
I just ran into this problem setting up a brand new project and had to make the same patch but on macos.
